- concreate/cli.py
- concreate/generator.py
This is preparation to extend CLI to be able to add more functions to the tool.
AS part of this prepration everything was moved to the 'build' subcomand.
Fixes #10
> Redefine CLI

- concreate/schema/image_schema.yaml
- concreate/schema/overrides_schema.yaml
Releases should be tagged in the repository.
Fixes #23.
> Remove 'release' key from schema

- concreate/cli.py
It additionally redefines where we define arguments in CLI.
concreate --descriptor=image.yaml generate
> Introduce generate target

- README.rst
- docs/configuration.rst
> Small doc tweaks/spelling/etc

- concreate/descriptor.py
- concreate/schema/image_schema.yaml
- concreate/schema/overrides_schema.yaml
- concreate/template_helper.py
- concreate/templates/template.jinja
- docs/descriptor.rst
- tests/test_dockerfile.py
> Move 'user', 'workdir', 'cmd' and 'entrypoint' keys to 'run' section

- concreate/descriptor.py
- concreate/schema/module.yaml
- concreate/templates/template.jinja
> Refactored module execute section.

- concreate/cli.py
- concreate/descriptor.py
- concreate/resource.py
- concreate/tools.py
* Fixed typo for resource description
* Description is displayed when handling of resource fails
* Fixed handling of 'path' resources with cache enabled
> Fix handling artifacts defined in modules

- concreate/version.py
Signed-off-by: Marek Goldmann <mgoldman@redhat.com>
> Specify proper version

- concreate/log.py
- concreate/resource.py
- docs/installation.rst
- requirements.txt
- rpm/python-colorlog.spec
- rpm/python-concreate.spec
- rpm/python-docopt.spec
- rpm/python-pykwalify.spec
- tests/test_unit_resource.py
Required spec files to support the concreate COPR:
https://copr.fedorainfracloud.org/coprs/goldmann/concreate/
dnf install python3-concreate
yum install python2-concreate
Fixes #44.
> Add required spec files to create RPMs

- concreate/builders/osbs.py
This fixes some Python 3 incompatibility.
> Make sure everything is decoded properly

- concreate/descriptor.py
- concreate/schema/common.yaml
- concreate/templates/template.jinja
- docs/descriptor.rst
- tests/test_dockerfile.py
> Add missing volume information in schema

- concreate/test/collector.py
Signed-off-by: Marek Goldmann <mgoldman@redhat.com>
> Update step repository location

- concreate/builders/osbs.py
> OSBS - commit repos directory even if its removed

- concreate/cli.py
- concreate/descriptor.py
- concreate/generator.py
- concreate/module.py
- docs/descriptor.rst
- docs/index.rst
- docs/modules.rst
- docs/overrides.rst
- tests/test_unit_collector.py
Partially fixes #92 
WE should introduce a module versioning and enable proper module overrides.
> Fix modules overrides

- concreate/resource.py
> Updated URLResource to try to use url directly if cacher miss occurs.

- concreate/descriptor.py
- concreate/module.py
if there are not any other modules repositories defined.
> Added backward compatibility for implicit usage of local modules

- concreate/test/collector.py
- tests/test_unit_collector.py
> Fix test execution if tests are in modules and in image repository

- concreate/builders/osbs.py
This is a workaround for an issue with rphkg where it does not
honor any modifications to files done after running rhkg new-sources.
Fixes #122
> Fix issue with rhpkg new-sources

- rpm/python-concreate.spec
> Concreate rpm is missing git as dependency

- concreate/tools.py
- tests/modules/repo_1/module.yaml
- tests/modules/repo_1/script
- tests/modules/repo_2/module.yaml
- tests/modules/repo_2/script
- tests/test_validate.py
Dictionaries can be also Descriptor classes now.
> Fixed merging of dictionaries

- rpm/python-concreate.spec
I'm not sure if future should be added to requirements.txt.
> Missing builtins module for RHEL/CentOS/SL - fix #138

- concreate/descriptor/image.py
- tests/test_dockerfile.py
- tests/test_unit_tools.py
> Persisting concreate version in 'org.concrt.version' label

- concreate/builders/osbs.py
- concreate/cli.py
- docs/build.rst
- tests/test_unit_args.py
With this option rhpkg container-build is run with --nowait option
> implemented --build-osbs-nowait option

- concreate/descriptor/__init__.py
- concreate/descriptor/packages.py
- concreate/generator.py
- concreate/templates/template.jinja
- tests/test_unit_descriptor.py
Concreate was chaged in a way, that existing repositories in image
are not disabled during build phase. This enables easy community
images development.
> Image repositories are not disabled by yum anymore

- concreate/builders/osbs.py
> Concreate now reports build type for OSBS (scratch or release) one

- concreate/descriptor/packages.py
- concreate/templates/template.jinja
- tests/test_unit_descriptor.py
fixed issues introduce by #187
> fixed repository handling

- cekit/builders/docker.py
- cekit/builders/osbs.py
- cekit/cli.py
- docs/build.rst
- tests/test_builder.py
- tests/test_unit_args.py
> Added support for rhpkg-stage via --build-osbs-stage option

- cekit/builders/docker.py
- cekit/cli.py
- docs/build.rst
- tests/test_unit_args.py
if you run Cekit with --build-pull it asks builder to fetch latest
base image
> Implemented --build-pull option

- cekit/descriptor/base.py
- cekit/descriptor/image.py
- cekit/descriptor/module.py
- cekit/descriptor/modules.py
- cekit/descriptor/overrides.py
- cekit/descriptor/resource.py
- cekit/generator.py
- cekit/module.py
- docs/descriptor.rst
- tests/test_dockerfile.py
- tests/test_unit_module.py
- tests/test_unit_resource.py
- tests/test_unit_tools.py
> Artifats are now relative to the descriptor that introduced them

- bash_completion/cekit
- cekit/builders/osbs.py
- cekit/cli.py
- cekit/generator/base.py
- docs/build.rst
- tests/test_builder.py
- tests/test_unit_args.py
--build-osbs-target options is now passed to rhpkg as --target option
fixes #219
> implemented support for rhkpg --target option

- cekit/builders/osbs.py
> Running git add for modules directory with --all option for compatibility reasons

- cekit/descriptor/__init__.py
- cekit/descriptor/base.py
- cekit/descriptor/execute.py
- cekit/descriptor/module.py
- cekit/generator/base.py
- tests/modules/repo_3/mod_1/module.yaml
- tests/modules/repo_3/mod_2/module.yaml
- tests/modules/repo_3/mod_3/module.yaml
- tests/modules/repo_3/mod_4/module.yaml
- tests/modules/repo_3/mod_5/module.yaml
- tests/modules/repo_3/mod_6/module.yaml
- tests/modules/repo_3/mod_7/module.yaml
- tests/modules/repo_3/mod_8/module.yaml
- tests/modules/repo_3/mod_9/module.yaml
- tests/test_validate.py
Merging was changed to be bottom up with merging execute blocks before
their parent. This should carry whole subrtrees up in proper places.
> All execute section should now be ordered properly.

- cekit/descriptor/packages.py
- tests/modules/repo_4/mod_1/module.yaml
- tests/modules/repo_4/mod_2/module.yaml
- tests/modules/repo_4/mod_3/module.yaml
- tests/modules/repo_4/mod_4/module.yaml
Made log message nicer when an yum repo is not found in .cekit/config .
fixes #245
> Fixed log message for not found old-style repo

- cekit/generator/base.py
> removed architecture label from injected Red Hat default labels

- completion/bash/cekit
- completion/zsh/_cekit
- rpm/python-cekit.spec
Completion files were moved to separate packages.
> Add support for ZSH completion

- cekit/cache/__init__.py
- cekit/cache/artifact.py
- cekit/cache/cli.py
- cekit/cli.py
- cekit/crypto.py
- cekit/descriptor/resource.py
- cekit/tools.py
- docs/caching.rst
- docs/configuration.rst
- docs/descriptor/artifacts.rst
- docs/handbook.rst
- setup.py
- tests/test_unit_module.py
- tests/test_unit_resource.py
- tests/test_validate_cache.py
This commit introduces cekit-cache command.
Cekit now automatically caches all artifacts used to build image into
~/.cekit/cache.
you can interatc with this cache also via cekit-cache command.
>  Implemented caching.

- cekit/cache/artifact.py
- cekit/cli.py
- cekit/descriptor/base.py
- cekit/descriptor/execute.py
- cekit/descriptor/resource.py
- docs/overrides.rst
- tests/test_unit_descriptor.py
- tests/test_unit_resource.py
- tests/test_validate_cache.py
If you set any attribute to in YAML to None(~) it will be removed
> Implemented a way to remove any key

- cekit/cli.py
Split the run() method into a configure() method and a run()
method that calls it.
This means we can write tests for the configure() code without
invoking run() and generating Dockerfiles etc.
(Review tip: try ignoring whitespace changes with "git show HEAD -w")
> Split Cekit.run into run, configure

- cekit/cli.py
- cekit/test/runner.py
- docs/test.rst
Cekit now have ``--test-name`` switch whcih can be used to run
specific scenario only
> Implemented way to run particlar test scenario only

- cekit/builders/osbs.py
- cekit/cli.py
- completion/bash/cekit
- completion/zsh/_cekit
- docs/build.rst
- tests/test_builder.py
Added new option `--build-osbs-commit-msg` which you can use to
specify custom commit message for dist-git
> Custom commit message for dist-git

- cekit/descriptor/run.py
- docs/overrides.rst
- tests/test_unit_tools.py
> Fix cmd merging

- cekit/descriptor/run.py
- tests/test_unit_tools.py
Signed-off-by: rcernich <rcernich@redhat.com>
> #308 fix merge issues with run element

- cekit/cli.py
- tests/test_validate.py
The test command now is not generating Dockerfile. It also doesn't
fetch any artifacts and is not processing any package repositories.
> Test are not executing full generate anymore.

- cekit/cli.py
- cekit/config.py
- cekit/generator/base.py
- cekit/templates/template.jinja
- completion/bash/cekit
- completion/zsh/_cekit
- docs/build.rst
- tests/test_dockerfile.py
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
Allow to choose between `yum` or `microdnf` package managers
Fix https://github.com/cekit/cekit/issues/328
> Added microdnf support

- cekit/test/runner.py
> If tests fail, return with exit code 1 

- cekit/descriptor/image.py
- cekit/descriptor/packages.py
- tests/test_validate.py
Signed-off-by: rcernich <rcernich@redhat.com>
> issue #340: ensure content_set settings are merged into image from overrides

- cekit/templates/template.jinja
Signed-off-by: rcernich <rcernich@redhat.com>
> issue #343 ensure repos exist before running yum commands

- cekit/config.py
- cekit/descriptor/packages.py
Fix for #344.
Signed-off-by: rcernich <rcernich@redhat.com>
> issue #344 don't fail on missing repositories, unless they're actually used by the image

- cekit/descriptor/osbs.py
- cekit/generator/osbs.py
Additionally, make sure the target directory exists.
Fixes #347
> Generate container.yaml file

- cekit/builders/docker_builder.py
Now the Docker client is prepared the correct way by allowing to specify the timeuout via DOCKER_TIMEOUT environment variable.
Default value is 600. This is 10 minutes.
Fixes #350
> Add possiblity to pass timeout to Docker client

- docs/installation.rst
> Update installation documentation

- cekit/templates/template.jinja
- tests/test_dockerfile.py
> Do not install documentation packages as part of yum/microdnf install

- cekit/template_helper.py
- cekit/templates/template.jinja
- tests/modules/repo_packages/packages_module/module.yaml
- tests/modules/repo_packages/packages_module_1/module.yaml
- tests/test_validate.py
> Make sure the package cache is built and cleaned up when packages are installed

- docs/installation.rst
> Use curl to install COPR repo file on CentOS/RHEL

- docs/installation.rst
> fix copr installation step on installation.rst

- setup.py
> Remove concreate binary

- cekit/builders/osbs.py
- tests/test_builder.py
> Call brew/koji directly to submit the task to build in OSBS

- cekit/builder.py
- cekit/builders/docker_builder.py
- cekit/cli.py
- tests/test_builder.py
- tests/test_validate.py
> Make squashing in Docker optional

- cekit/templates/template.jinja
- tests/test_dockerfile.py
> Do not install modules if there are none to install

- .pylintrc
- cekit/cache/artifact.py
- cekit/cache/cli.py
- cekit/crypto.py
- cekit/descriptor/resource.py
- tests/test_unit_resource.py
- tests/test_unit_tools.py
- tests/test_validate_cache.py
> Cache command improvements

- cekit/generator/docker.py
- cekit/tools.py
- tests/test_expose_services.py
- tests/test_unit_generator_docker.py
- tests/test_validate.py
> Add support for unpublished pulp repositories

- cekit/descriptor/resource.py
- tests/test_unit_resource.py
Addiitonally added a bit more logging.
Fixes #411
> Fix usage of plain resources with cache_url specified

- .circleci/config.yml
> Build documentation on CI too

- cekit/builders/buildah.py
- cekit/builders/podman.py
- cekit/generator/docker.py
- tests/test_builder.py
- tests/test_unit_generator_docker.py
- tests/test_validate.py
> Fix tagging of podman/buildah images

- cekit/builders/docker_builder.py
- tests/test_builder.py
> Make sure Docker build is tagged with all tags

- docs/conf.py
- docs/descriptor/artifacts.rst
- docs/descriptor/image.rst
- docs/redhat.rst
> Rewrite of artifacts documentation

- docs/caching.rst
- docs/configuration.rst
- docs/redhat.rst
Additionally, the configuration documentation was updated too.
Fixes #449
> Caching documentation rewrite

- cekit/tools.py
- tests/test_unit_tools.py
> Fix parsing of /etc/os-release files

- cekit/descriptor/resource.py
> Bump chunk size for downloading files to 1MB

- cekit/templates/template.jinja
- tests/test_dockerfile.py
> Do not run makecache when microdnf manager is used

- cekit/cli.py
> Improve error handling around directory cleanup.

- cekit/descriptor/image.py
- cekit/descriptor/packages.py
- tests/test_dockerfile.py
Actually merge pacakge manager if defined in any overrides. Additionally
default value should be applied at the end.
Fixes #462
> Fix merging package manager

- cekit/cli.py
- tests/test_integ_test_behave.py
- tests/test_unit_args.py
> Add support for using overrides in test command

- cekit/builders/docker_builder.py
- tests/test_unit_builder_docker.py
> Handle properly layer ids in case we need to print them

- cekit/builders/osbs.py
- tests/test_builder.py
> Add support for git 1.8 in fetching origin url

- cekit/generator/base.py
- cekit/generator/docker.py
- tests/test_unit_generator_docker.py
Fixes a few things:
1. Makes it possible to request ODCS composes for local builder
other than Docker
2. Makes it possible to request ODCS compose using community service
Fixes #491
> ODCS compose enhancements

- cekit/templates/template.jinja
- tests/test_dockerfile.py
- tests/test_validate.py
> Do not invoke pkg_manager makecache

- cekit/builders/osbs.py
- tests/test_integ_builder_osbs.py
Additionally adds first integration tests for OSBS builder and
simplifies the code in some places.
Fixes #504
> Make sure image help files are added when used with OSBS builder

- cekit/builders/docker_builder.py
- tests/test_unit_builder_docker.py
> Handle tagging images in Docker builder with multiple colons

- cekit/tools.py
- tests/test_unit_tools.py
Besides handling failures in brew call it tries to suggest actions
when a possible authentication failure is happening.
Fixes #502
> Improvements in handling Kerberos issues while fetching Brew artifacts

- cekit/builders/docker_builder.py
- tests/test_unit_builder_docker.py
> Use automatic decoding of message stream from Docker daemon

- cekit/builders/docker_builder.py
> Ignore unnecessary logs from Docker builder

- .circleci/config.yml
- Pipfile
- cekit/generator/base.py
- cekit/generator/docker.py
- tests/test_dockerfile.py
- tests/test_unit_generator_docker.py
- tests/test_validate.py
> Use Python library to request ODCS composes

- cekit/builders/docker_builder.py
- docs/handbook/building/builder-engines.rst
- tests/test_validate.py
> Use DOCKER_* environment variables to properly create Docker client

- docs/getting-started/modules.rst
> Fix formatting for Tomcat module in getting started guide

- cekit/builders/osbs.py
- cekit/descriptor/base.py
- cekit/generator/base.py
- tests/test_integ_builder_osbs.py
- tests/test_validate.py
> Refactoring, skipping .git directory from adding to dist-git

- docs/getting-started/modules.rst
> Clarify module section in docs.

- support/completion/zsh/_cekit
> Fix for ZSH completion

- docs/handbook/building/builder-engines.rst
> Extend documentation about Docker environment variables

- docs/guidelines/local-development.rst
- docs/handbook/modules/merging.rst
* Added information about the name key
* Moved note about module install and caching
* Other small formatting improvements
Fixes #527
> Extend local module development documentation

- cekit/cli.py
- cekit/generator/base.py
- docs/handbook/building/builder-engines.rst
- tests/test_validate.py
Additionally added documentation about this switch.
Fixes #559
> Deprecate OSBS --tech-preview switch

- docs/guidelines/modules/index.rst
- docs/guidelines/modules/naming.rst
> Add module naming suggestion to guidelines

- cekit/builder.py
- cekit/builders/buildah.py
- cekit/builders/docker_builder.py
- cekit/builders/osbs.py
- cekit/builders/podman.py
- cekit/cli.py
- cekit/generator/base.py
- cekit/test/behave_runner.py
- cekit/test/behave_tester.py
- cekit/test/collector.py
- cekit/tools.py
- pytest.ini
- tests/test_builder.py
- tests/test_integ_addhelp.py
- tests/test_unit_args.py
- tests/test_unit_builder_docker.py
- tests/utils.py
> Use command line options to determine what required libraries to check for

- docs/guidelines/artifacts.rst
- docs/guidelines/index.rst
> Add initial best practices around artifacts

- docs/descriptor/includes/artifacts.rst
- docs/handbook/index.rst
- docs/handbook/multi-stage.rst
> Multi-stage builds documentation

- cekit/builder.py
- cekit/cli.py
- cekit/generator/base.py
- docs/descriptor/includes/from.rst
- docs/handbook/building/builder-engines.rst
- tests/test_dockerfile.py
- tests/test_unit_args.py
- tests/test_validate.py
Overrides should be used instead.
Fixes #600
> Remove --tech-preview switch from OSBS builder

- cekit/descriptor/packages.py
- cekit/template_helper.py
- cekit/templates/template.jinja
- docs/descriptor/includes/packages.rst
- tests/images/alpine/image.yaml
- tests/images/alpine/modules/app/install.sh
- tests/images/alpine/modules/app/module.yaml
- tests/test_dockerfile.py
- tests/test_integ_multi_stage.py
- tests/test_integ_podman.py
- tests/test_validate.py
This adds support for apk package manager used in Alpine Linux.
Fixes #609
> Add support for apk package manager (Alpine Linux)

- cekit/descriptor/resource.py
- cekit/templates/template.jinja
- docs/descriptor/includes/artifacts.rst
- docs/handbook/index.rst
- docs/handbook/scratch.rst
- tests/images/multi-stage-scratch/image.yaml
- tests/images/multi-stage-scratch/modules/build/build.sh
- tests/images/multi-stage-scratch/modules/build/hello-world.go
- tests/images/multi-stage-scratch/modules/build/module.yaml
- tests/images/operator-metadata/image.yaml
- tests/images/scratch/image.yaml
- tests/images/scratch/metadata/test-file.txt
- tests/test_builder.py
- tests/test_dockerfile.py
- tests/test_integ_multi_stage.py
- tests/test_integ_podman.py
- tests/test_integ_test_behave.py
- tests/test_unit_descriptor.py
This commit adds support for building container images
using the special base iamge 'scratch'. Using this feature
requires that image is prepared in smart way and not every
module will work because the base image is empty and does
not provide any libraries.
A common use case for this type of images is to use it as
metadata images or to store binary builds (potentially
being a result of mult-stage builds).
To support these use cases a new property was added to resources:
'dest'. This defines where the artifact should be placed within the image.
https://github.com/cekit/cekit/issues/487
> Add support for 'FROM scratch'

- tests/test_dockerfile.py
> Add a test to ensure overrides are applied to all multi-stage images

- docs/handbook/multi-stage.rst
- docs/handbook/scratch.rst
Additionally a few minor updates to scratch image documentation
were performed.
Fixes #647
> Mention which keys are not relevant when running multi-stage builds

- cekit/builders/docker_builder.py
- cekit/builders/osbs.py
- cekit/descriptor/base.py
- cekit/descriptor/osbs.py
- cekit/generator/base.py
- cekit/generator/docker.py
- cekit/generator/osbs.py
- cekit/template_helper.py
- cekit/templates/template.jinja
- docs/handbook/building/builder-engines.rst
- tests/test_integ_builder_osbs.py
Requires #661 to be dealt with first.
> Issue #663 / CPAAS-1206 Add integration for cachito

- Pipfile
- cekit/generator/osbs.py
- docs/requirements.txt
- requirements.txt
- tests/test_integ_builder_osbs.py
Awaiting #661 to be merged first.
> CPAAS1237 : Add description field as comment after URL

- docs/handbook/ci.rst
- docs/handbook/index.rst
> Issue #671: Add reference to github action

- cekit/descriptor/base.py
- cekit/descriptor/image.py
- cekit/descriptor/module.py
- tests/test_dockerfile.py
- tests/test_unit_descriptor.py
- tests/test_validate.py
> Issue #664: Remove execute from image descriptor

- cekit/descriptor/execute.py
- cekit/descriptor/volume.py
- tests/test_unit_descriptor.py
> Issue #616: Adjust logging output for internal name keys

- cekit/template_helper.py
- cekit/templates/template.jinja
- docs/descriptor/includes/packages.rst
- tests/test_dockerfile.py
- tests/test_validate.py
> Issue #668 : Add install_weak_deps=0 to microdnf invocations

- docs/descriptor/includes/envs.rst
- tests/test_validate.py
> Clarify documentation and add test for environment variables

- docs/contribution-guide/environment.rst
- docs/handbook/installation/dependencies.rst
- support/ansible/host_vars/localhost.yml
> Clarify dependencies for testing CEKit itself

- docs/handbook/ci.rst
> Update github action reference

- cekit/tools.py
- tests/test_integ_builder_osbs.py
> Handle pre-existing content when using extra_dir

- cekit/generator/base.py
- cekit/generator/osbs.py
- tests/test_validate.py
> Process inline path overrides correctly

- .circleci/config.yml
- .github/workflows/cekit.yml
- Makefile
- tox.ini
Adds an initial GitHub Action to run the tests.
> Add Python 3.8 to testing

- cekit/generator/osbs.py
- tests/test_integ_builder_osbs.py
> Fix incorrect indexing fo fetch-artifacts-url.yaml

- Pipfile
- requirements.txt
See https://pypi.org/project/odcs/0.3.2/#history
> CPAAS-1529 Revert ODCS version change to what Fedora provides

- docs/descriptor/includes/packages.rst
> Clarify microdnf and remote URLs

- cekit/cli.py
- cekit/log.py
- docs/handbook/installation/instructions.rst
- tests/test_dockerfile.py
- tests/test_integ_addhelp.py
- tests/test_integ_builder_osbs.py
- tests/test_integ_test_behave.py
- tests/test_unit_args.py
- tests/test_validate.py
- tests/test_validate_cache.py
> Add ability to disable color logging

- cekit/builders/osbs.py
- tests/test_builder.py
- tests/test_integ_builder_osbs.py
> Clean extra_dir location

- cekit/templates/template.jinja
- tests/test_integ_builder_osbs.py
> Add WORKDIR for Cachito support

- tests/test_builder.py
- tests/test_integ_builder_osbs.py
- tests/test_unit_builder_docker.py
> Remove unused test code

- cekit/descriptor/packages.py
- cekit/template_helper.py
- cekit/templates/template.jinja
- docs/descriptor/includes/packages.rst
- tests/test_dockerfile.py
> Add support for manager_flags

- cekit/descriptor/image.py
- cekit/descriptor/osbs.py
- cekit/descriptor/resource.py
- cekit/template_helper.py
- cekit/templates/template.jinja
- tests/images/rhpam/image.yaml
- tests/images/rhpam/modules/org.kie.kogito.builder/install.sh
- tests/images/rhpam/modules/org.kie.kogito.builder/module.yaml
- tests/images/rhpam/modules/org.kie.kogito.bundleinstall/module.yaml
- tests/images/rhpam/modules/org.kie.kogito.gomoddownloader/install.sh
- tests/images/rhpam/modules/org.kie.kogito.gomoddownloader/module.yaml
- tests/test_integ_builder_osbs.py
- tests/test_unit_tools.py
> Resolve handling multiple OSBS configuration blocks. Fix Cachito integration location

- requirements.txt
> Remove ODCS from requirements.txt for readthedocs

- cekit/builders/osbs.py
- cekit/cli.py
- cekit/config.py
- cekit/descriptor/packages.py
- cekit/descriptor/resource.py
- cekit/generator/osbs.py
- docs/handbook/building/builder-engines.rst
- docs/handbook/configuration.rst
- tests/test_integ_builder_osbs.py
- tests/test_unit_resource.py
> Suport fetch_allowed_domains

- .readthedocs.yml
- requirements.txt
> Restore odcs requirement and add readthedocs build configuration

- cekit/descriptor/osbs.py
- cekit/generator/base.py
- cekit/generator/osbs.py
- cekit/templates/help.jinja
- cekit/templates/template.jinja
- docs/descriptor/includes/help.rst
- docs/descriptor/includes/image/osbs.rst
- tests/test_integ_addhelp.py
- tests/test_validate.py
Fixes #737 
CC @jmtd , @AntStephenson and is for @kyguy
> Add support for custom gating.yaml and improved help documentation

- cekit/builders/osbs.py
- cekit/descriptor/resource.py
- cekit/generator/base.py
- cekit/generator/osbs.py
- docs/contribution-guide/releasing.rst
- docs/descriptor/includes/artifacts.rst
- docs/handbook/redhat.rst
- tests/test_integ_builder_osbs.py
- tests/test_unit_descriptor.py
- tests/test_unit_resource.py
Fixes #731 
Related : CPAAS-2078
> Add support for PNC artifact type

- cekit/descriptor/resource.py
- cekit/generator/osbs.py
- docs/handbook/redhat.rst
> Add documentation note

- cekit/builders/osbs.py
- cekit/descriptor/resource.py
- tests/test_integ_builder_osbs.py
> Fix lookaside when using PNC artifacts. Make target optional

- cekit/generator/osbs.py
- tests/test_integ_builder_osbs.py
> Fix artifact download location for PNC artifact types

- cekit/generator/base.py
- cekit/tools.py
- docs/handbook/cli.rst
- docs/handbook/index.rst
- tests/test_validate.py
> Enable reading descriptor from stdin

- cekit/descriptor/packages.py
- cekit/templates/template.jinja
- docs/descriptor/includes/labels.rst
- docs/descriptor/includes/packages.rst
- tests/test_validate.py
> Update documentation and remove unused schema elements

- docs/handbook/overrides.rst
- tests/test_validate.py
> Clarify YAML/JSON usage

- cekit/descriptor/resource.py
- tests/test_integ_builder_osbs.py
> Add progress bar for remote downloads

- cekit/descriptor/resource.py
- cekit/generator/base.py
- cekit/tools.py
- docs/handbook/overrides.rst
- tests/test_integ_builder_osbs.py
- tests/test_unit_resource.py
- tests/test_validate.py
> Support remote URLs for overrides-file command

- docs/contribution-guide/releasing.rst
> Add RPM build instructions

- cekit/builders/buildah.py
- cekit/builders/docker_builder.py
- cekit/builders/podman.py
- cekit/cli.py
- docs/handbook/building/builder-engines.rst
- tests/test_builder.py
- tests/test_integ_podman.py
- tests/test_unit_args.py
- tests/test_unit_builder_docker.py
- tests/utils.py
> Support platform command for multiple architectures

- Pipfile
- requirements.txt
> Drop ODCS version to 0.2.10

- cekit/builders/docker_builder.py
- tests/images/multi-stage/modules/build/module.yaml
> Resolve issues with Docker API version

- cekit/test/behave_tester.py
- cekit/version.py
- tests/test_integ_test_behave.py
> Default schema_version to current version for Behave testing

- tests/test_integ_test_behave.py
> Add test to verify image start arguments

- docs/handbook/building/builder-engines.rst
> Clarify image tagging command

- cekit/crypto.py
- cekit/descriptor/resource.py
- cekit/generator/osbs.py
- docs/descriptor/includes/artifacts.rst
- tests/test_integ_builder_osbs.py
- tests/test_unit_resource.py
Fixes #810 
Needs #811 merged first.
> Add support for source-url/hash to Plain and URL artifacts

- .github/workflows/cekit.yml
- cekit/builders/podman.py
- tests/test_builder.py
- tests/test_integ_install_ordering.py
- tests/test_integ_multi_stage.py
- tests/test_integ_podman.py
- tests/test_validate.py
Signed-off-by: spolti <fspolti@redhat.com>
> search podman binary instead hardcode to /usr/bin/podman

- cekit/builders/osbs.py
> Fix typing in OSBS builder

- .circleci/config.yml
- .github/workflows/cekit.yml
- cekit/builders/buildah.py
- cekit/builders/osbs.py
- cekit/generator/base.py
- cekit/tools.py
- docs/conf.py
- tests/test_builder.py
- tests/test_integ_builder_osbs.py
- tests/test_unit_tools.py
> Fix dependency checking

- cekit/generator/base.py
- cekit/generator/legacy_version.py
- requirements.txt
- tests/test_unit_image.py
> Handle upgraded packaging removal of LegacyVersion

- cekit/builder.py
- cekit/builders/osbs.py
- cekit/cli.py
- cekit/generator/base.py
- cekit/generator/behave.py
- cekit/generator/docker.py
- cekit/generator/osbs.py
- cekit/test/behave_tester.py
- docs/handbook/building/parameters.rst
- tests/test_builder.py
- tests/test_dockerfile.py
- tests/test_integ_multi_stage.py
- tests/test_unit_args.py
- tests/test_unit_generator_docker.py
- tests/test_validate.py
> Support Containerfile as well as Dockerfile

- cekit/descriptor/image.py
- cekit/descriptor/packages.py
- cekit/template_helper.py
- cekit/templates/template.jinja
- docs/conf.py
- docs/descriptor/includes/image/packages.rst
- docs/descriptor/includes/module/packages.rst
- docs/descriptor/includes/packages/common.rst
- docs/descriptor/includes/packages/reinstall.rst
- docs/descriptor/includes/packages/remove.rst
- docs/descriptor/includes/packages/repositories.rst
- docs/getting-started/modules.rst
- docs/handbook/modules/image_order.rst
- tests/test_dockerfile.py
- tests/test_validate.py
> Add package removal/reinstall functionality

- cekit/generator/base.py
- tests/test_dockerfile.py
> Avoid calling ODCS when Behave testing

- cekit/descriptor/execute.py
- cekit/descriptor/packages.py
- cekit/generator/base.py
- tests/test_dockerfile.py
> Remove unused code/invalid schema elements

- cekit/descriptor/env.py
- docs/descriptor/includes/envs.rst
- tests/test_dockerfile.py
- tests/test_unit_descriptor.py
- tox.ini
> Adjust env schema to permit extra keys

- cekit/builders/docker_builder.py
- cekit/config.py
- cekit/descriptor/resource.py
- cekit/generator/osbs.py
- docs/handbook/configuration.rst
> Fix TODO. Correct documentation.

- cekit/generator/base.py
- tests/test_dockerfile.py
- tests/test_validate.py
> Improve LegacyVersion fallback for all module versions

- cekit/builders/docker_builder.py
- cekit/cli.py
- cekit/descriptor/base.py
- cekit/descriptor/resource.py
- cekit/generator/base.py
- cekit/generator/osbs.py
- cekit/tools.py
> Improve exception handling and Python 36 subprocess compatibility

- .github/workflows/cekit.yml
- cekit/builders/buildah.py
- cekit/builders/docker_builder.py
- cekit/builders/podman.py
- cekit/cli.py
- cekit/descriptor/__init__.py
- cekit/descriptor/arg.py
- cekit/descriptor/image.py
- cekit/templates/template.jinja
- cekit/tools.py
- docs/descriptor/common_keys.rst
- docs/descriptor/includes/args.rst
- docs/descriptor/includes/module/execute.rst
- tests/test_builder.py
- tests/test_dockerfile.py
- tests/test_unit_args.py
- tests/test_unit_descriptor.py
- tests/test_unit_tools.py
> Add support for ARG

- Pipfile
- cekit/builder.py
- cekit/generator/base.py
- cekit/tools.py
- requirements.txt
- tests/test_validate.py
> Only require odcs client when using content_sets

- docs/getting-started/modules.rst
- docs/handbook/building/build-process.rst
- docs/handbook/modules/image_order.rst
- docs/handbook/modules/merging.rst
Digraph diagrams are in:
- getting-started/modules.rst
- handbook/building/build-process.rst
- handbook/modules/image_order.rst
- handbook/modules/merging.rst
> Adapt colors in digraph for light/dark

- cekit/builders/docker_builder.py
- cekit/builders/osbs.py
- cekit/generator/base.py
- cekit/tools.py
- docs/handbook/cli.rst
- docs/handbook/configuration.rst
- tests/test_builder.py
- tests/test_unit_tools.py
> Expose timeouts as environment variables

- docs/handbook/installation/dependencies.rst
- tests/images/multi-stage/image.yaml
- tests/images/multi-stage/modules/python/module.yaml
- tests/test_integ_builder_osbs.py
> Remove note about old docker library

- cekit/builders/osbs.py
- cekit/tools.py
- docs/descriptor/includes/artifacts.rst
- docs/handbook/configuration.rst
- tests/test_unit_resource.py
- tests/test_validate.py
> Add URL authentication

- .github/workflows/cekit.yml
Tried with MacOS 15 but doesn't appear to support virtualisation
```
Error: Error Domain=VZErrorDomain Code=2 Description="Invalid virtual machine configuration. Virtualization is not available on this hardware." UserInfo={
NSLocalizedFailure = "Invalid virtual machine configuration.";
NSLocalizedFailureReason = "Virtualization is not available on this hardware.";
}
```
> MacOS Fixes

- .circleci/config.yml
- cekit/builders/docker_builder.py
> Add logging

- .github/workflows/cekit.yml
- cekit/builders/buildah.py
- cekit/builders/docker_builder.py
- cekit/builders/oci_builder.py
- cekit/builders/podman.py
- cekit/cli.py
- docs/handbook/building/builder-engines.rst
- tests/test_builder.py
- tests/test_unit_args.py
- tests/test_unit_builder_docker.py
> Add build-tool support. Invoke Docker CLI for buildkit scenarios

- cekit/template_helper.py
- cekit/templates/template.jinja
- support/run_formatter.py
- tests/test_dockerfile.py
- tests/test_validate.py
> Simplify template.jinja and helper

- .github/workflows/cekit.yml
For https://www.github.com/actions/runner-images/issues/11101
> Update ubuntu runner

- docs/handbook/modules/merging.rst
> Clarify use of artifacts for modules

- cekit/descriptor/arg.py
- cekit/descriptor/env.py
- docs/descriptor/includes/args.rst
- tests/test_unit_descriptor.py
> Add ability to specify example/description for args

- cekit/descriptor/image.py
- docs/descriptor/includes/help.rst
- tests/test_integ_addhelp.py
- tests/test_unit_tools.py
> Support help template in modules
