cekit/cekit

concreate/generator.py
concreate/tools.py
tests/test_unit_tools.py

When a file exists on disk and the checksum is not correct
we should try to download that file again and fail
if the checksum after download is still not correct.
Fixes #9

If verification of artifact failed - try to download it again

---

.stickler.yml
concreate/descriptor.py
concreate/schema/image_schema.yaml
concreate/schema/overrides_schema.yaml
tests/test_unit_descriptor.py

Labels description and summary are set up correctly based on the description key in the image descriptor.
See code for more information.
Fixes #12

Better processing of important labels

---

concreate/cli.py
concreate/generator.py

It's now possible to override default tags using the --build-tag
parameter. Multiple tags can be specified.
Fixes #33.

Add support for specifying custom tags for the build target

---

concreate/descriptor.py

Adding a prefix here results in adding it twice later which fails builds that are
executed in a directory not being the same as image.yaml.

Do not add directory prefix to added modules

---

concreate/builders/osbs.py
concreate/version.py
rpm/python-concreate.spec

OSBS builder will not die if there are no artifacts for rhpkg new-sources command

---

docs/test.rst

Some changes to the test documentation page based in part on some older documentation from before we used concreate.

test documentation overhaul

---

concreate/descriptor.py
concreate/module.py
concreate/tools.py
tests/test_unit_tools.py

Now we are working with Descriptor classes instead of dictionaires for
merging, so we can move merging logic to the domain of descriptor class

Simplified merging code

---

concreate/builders/osbs.py
concreate/cli.py
concreate/tools.py
docs/configuration.rst
tests/test_unit_args.py

Location of Concreate config file can now be parametrized via --config
option as follows:
``` sh
concreate --config path ...
```
If parameter is not specified it defaults to ~/.concreate
Config file also contains new common key `workdir` which specifies
working directory for concreate. Defaults to ~/.concreate.d
example
```
[common]
work_dir = ~/whatever
```
fixes #172

Parametrizing config file location

---

concreate/descriptor/image.py
concreate/descriptor/module.py
concreate/descriptor/overrides.py
tests/test_unit_descriptor.py
tests/test_unit_tools.py

It seems that iamge_schema got overriden by override schema, so name
key was not mandatory.
I've fixed it by exposing only deep copy of image_schema.

Fixed Image schema validaiton

---

concreate/template_helper.py
concreate/templates/template.jinja
concreate/version.py
tests/test_unit_template_helper.py

com.redhat.component label is now generated only if not present in image descriptor
Signed-off-by: David Becvarik <dbecvari@redhat.com>

com.redhat.component label is now generated only if not present in image descriptor

---

cekit/builder.py
cekit/builders/buildah.py
cekit/cli.py
docs/build.rst
tests/test_builder.py
tests/test_unit_args.py

--build-engine now accepts buildah as a builder. You need to have
buildah installed and sudo configure to run buildah as a root on you
computer.

Implemented basic buildah support

---

tests/test_validate.py
tox.ini

These tests need Docker properly installed and configured and this
is causing troubles on some CI.
To enable these tests run
``` bash
export CEKIT_TEST_VALIDATE=y
make
```
in the Cekit project root.

Run validation tests only if CEKIT_TEST_VALIDATE env is set.

---

bash_completion/cekit
cekit/cli.py
docs/build.rst
docs/configuration.rst
tests/test_unit_args.py

Common section configuration option 'work_dir' can now be overriden
via --work-dir command lines option
Fixes #223

Implemented --work-dir option switch

---

docs/overrides.rst

the link to issue #106 in the documentation pointed to an old repository that no longer exists. this change refreshes the link to its current location.

update overrides bug link

---

cekit/builders/buildah.py
tests/test_builder.py

When invoking buildah with _pull=True, use the --pull-always option.

Fix a typo

---

cekit/builders/osbs.py
cekit/generator/base.py
tests/test_dockerfile.py

If we define only repo files urls, rhpkg is run with --repos-url
option
If we have at least one pulp repo enabled its passed to container.yaml
and content_sets.yml files and url repos are download and injected
into Dockerfile.

Updated OSBS builder to handle repositories properly.

---

cekit/descriptor/execute.py
cekit/generator/base.py
cekit/generator/docker.py
tests/test_dockerfile.py

renamed _use_odcs to _fetch_repos in generator which describes more
what it does and changed it to be True for Docker generator by default

Encapsulated decriptor iterator into list to be reversible

---

cekit/cli.py
cekit/generator/base.py
cekit/templates/help.jinja
cekit/templates/template.jinja
cekit/tools.py
docs/build.rst
docs/configuration.rst
tests/test_addhelp.py

This is a bit WIP still but raising PR for feedback. My own list of things still todo
Example of output docs: https://github.com/jmtd/redhat-openjdk-18-openshift-image/blob/help-pages/target/image/help.md

Container help pages

---

cekit/cli.py
completion/bash/cekit
completion/zsh/_cekit
tests/test_unit_args.py

This was marked as deprecated and for removal in 2.0.

Remove --build-tag argument

---

cekit/descriptor/image.py
cekit/generator/base.py
docs/descriptor/help.rst
docs/descriptor/image.rst
docs/handbook.rst
docs/image_help_pages.rst
tests/test_addhelp.py

I think this is likely to be the way this is most often used in
practice. An image author may wish to provide a custom help.md file,
potentially containing long-form static text, either directly in an
image.yaml, or indirectly via a module (perhaps to share with a
family of images).
<s>I've marked this WIP because I think the precedence should be
> defined in config < defined in image.yaml (post module processing) < defined on cmdline
But right now that's not how things are, config file trumps image.yaml,
and we haven't implemented command line argument for this at all.</s>
precedence fixed; let's not add a new cmdline argument, instead users could do `--overrides { help: template: foo.md }` or similar

Support defining help_template in image.yaml

---

cekit/generator/base.py
tests/test_expose_services.py

Only generate io.openshift.expose-services if there are ports
defined.

io.openshift.expose-services only if ports defined

---

cekit/module.py
tests/issue_322/image.yaml
tests/issue_322/modules/a/module.yaml
tests/issue_322/modules/b/module.yaml
tests/issue_322/modules/c/module.yaml
tests/issue_322/modules/d/module.yaml
tests/test_unit_module.py

Module objects may not have a 'version' attribute, so check that
it exists before trying to access it.
Fixes #322.

Ensure Module object has attribute before accessing it

---

cekit/descriptor/resource.py

The adjoining \" and """ cause syntax-highlighter problems in Vim.

add newline at the end of string literal

---

cekit/cache/artifact.py

In case we try to find an artifact by a specific alrorithm
and this algorithm is not computed for some artifacts
it will fail. Instead of failing, it should simply not return the
artifact.

Fix KeyError when fetching the artifact

---

cekit/builders/osbs.py
cekit/test/runner.py
cekit/tools.py
tests/test_addhelp.py
tests/test_expose_services.py
tests/test_validate.py

Instead of writing it to the current directory, write test output to target/tests/ directory.
Fixes #335.

Fix test output directory

---

cekit/builders/osbs.py
cekit/descriptor/resource.py
cekit/generator/docker.py
cekit/generator/osbs.py
cekit/tools.py
tests/test_validate.py

If the artifact is a plain artifact and it does not exists in Brew, OSBS builds is failing.
It was fixed by falling back into the regular procedure (check local, remote cache).
If this fails, the build fails. If it doesn't, OSBS will use a mix of artifacts:
fetched using fetch-artifacts-url.yaml and from lookaside cache. Approriate
warnings are added.

Fix support in plain artifacts handling for OSBS

---

cekit/descriptor/image.py
cekit/descriptor/osbs.py
cekit/descriptor/packages.py
tests/test_unit_descriptor.py

When you specify container_file or content_sets_files in your image
descriptor, these locations will be relative to the directory
where image descriptor is stored.

Paths to content_sets and container files should be relative to descriptor

---

cekit/test/runner.py

When diagnosing test problems, it can be helpful to run "behave"
by hand. It's useful to know exactly how cekit was invoking "behave",
to figure out what tags are selected or de-selected, etc.
Log (to debug logger) the collected arguments prior to starting
"behave".

Debug-log arguments collected for "behave"

---

cekit/builders/osbs.py
tests/test_builder.py

The issue was that if an artifact had the 'target' kwy set,
the OSBS builder incorrectly skipped it and tried to use 'name'.
Fixes #414

Properly define what artficats should be copied to dist-git

---

cekit/tools.py
tests/test_unit_tools.py

We should fetch artifacts only when the build is in COMPLETE state.
In all other cases, build is in incorrect state, we should not fetch
any artifacts in such case.
Fixes #415

Do not download artifacts from unsuccessful builds

---

.gitignore
.pylintrc
Pipfile
cekit/builder.py
cekit/builders/buildah.py
cekit/builders/docker_builder.py
cekit/builders/osbs.py
cekit/cache/artifact.py
cekit/cache/cli.py
cekit/cli.py
cekit/config.py
cekit/descriptor/base.py
cekit/descriptor/resource.py
cekit/generator/base.py
cekit/generator/docker.py
cekit/generator/osbs.py
cekit/log.py
cekit/test/behave.py
cekit/test/collector.py
cekit/tools.py
setup.py
tests/test_addhelp.py
tests/test_builder.py
tests/test_dockerfile.py
tests/test_expose_services.py
tests/test_unit_args.py
tests/test_unit_tools.py
tests/test_validate.py
tests/test_validate_cache.py
tox.ini

CLI rewrite

---

support/completion/bash/cekit
support/completion/zsh/_cekit

With this the autocompletion feature for Click apps is enabled:
https://click.palletsprojects.com/en/7.x/bashcomplete/
These snippets were generated using following commands:
_CEKIT_COMPLETE=source cekit
_CEKIT_CACHE_COMPLETE=source cekit-cache
_CEKIT_COMPLETE=source_zsh cekit
_CEKIT_CACHE_COMPLETE=source_zsh cekit-cache
Fixes #423

Make shell completion files generic

---

cekit/descriptor/packages.py
tests/test_unit_descriptor.py

This removes support for repositories defined this way:
```yaml
repositories:
- repo-foo
- repo-bar
```
and defined in the CEKit configuration file.
Fixes #386

Remove support for old style repositories

---

Pipfile
cekit/cli.py
cekit/config.py
cekit/descriptor/packages.py
cekit/generator/base.py
cekit/template_helper.py
cekit/templates/template.jinja
docs/CONTRIBUTING.rst
docs/build.rst
docs/conf.py
docs/descriptor/artifacts.rst
docs/descriptor/module.rst
docs/descriptor/osbs.rst
docs/descriptor/packages.rst
docs/installation/instructions.rst
docs/repository_management.rst
docs/testing/behave.rst
tests/test_dockerfile.py
tests/test_unit_args.py

This removes support for defining package manager used to install packages
from the command line (and configuration file) to the image descriptor
itself.
Adds support for dnf.
Fixes #400

Move support for defining package managers to image definition

---

cekit/cli.py
cekit/test/behave_runner.py
cekit/test/behave_tester.py
cekit/test/collector.py
tests/test_integ_test_behave.py
tests/test_unit_args.py
tests/test_unit_collector.py

The issue was that the search for the behave module was shaded by the `behave.py` file. Added basic test to make sure we can execute tests.

Make Behave tester work again

---

cekit/cache/cli.py
cekit/crypto.py
cekit/descriptor/resource.py
docs/descriptor/includes/artifacts.rst
docs/handbook/caching.rst
tests/test_unit_resource.py
tests/test_validate_cache.py

This change brings in the `sha512` as a possible key for checksum values
associated with the `artifact` directive. It also updates the relevent
tests and documentation.
closes issue #471

add sha512 as an optional checksum

---

cekit/descriptor/image.py
cekit/descriptor/module.py
cekit/descriptor/modules.py
cekit/descriptor/packages.py
tests/test_validate.py

This fix makes sure that when a package or modules is defined in
overrides only it gets added to the resulting image.
Same applies to artifacts.
Fixes #489

Modules and packages defined in overrides are not ignored anymore

---

cekit/templates/template.jinja

I wonder, it's a little weird putting RH in the default template, I suppose a future feature might be some way of extracting that and permitting people to inject their own. But so long as its there, let's bump the year

Bump copyright year in the template

---

cekit/generator/base.py
tests/test_unit_generator_docker.py

I was unsure about where to add the unit test, please fell free to ask to move/change this one to some other place. The `yaml` and `Image` imports seems odd in this test case.
Fixes #506
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

Add a line break to large labels

---

cekit/builders/osbs.py
cekit/descriptor/image.py
cekit/descriptor/osbs.py
cekit/generator/base.py
cekit/generator/osbs.py
cekit/tools.py
docs/descriptor/includes/image/osbs.rst
tests/test_builder.py
tests/test_dockerfile.py
tests/test_integ_builder_osbs.py

If a directory called `dist` is found next to the image descriptor,
contents of this directory will be copied to the **root** of the
dist-git directory.
Fixes #394.

Allow for supplementary files to be added to dist-git repository

---

cekit/tools.py
tests/test_unit_tools.py

When an artifact contains dot in the name and it is used
in the fetch-artifacts-url.yaml, the generated URL
is wrong and instead of preserving the dot it is converted to a slash.
Fixes #531

Dots in artifact name should not be replaced with slashes

---

cekit/builder.py
cekit/builders/osbs.py
tests/test_builder.py

This was made possible due to refactoring and
enabling additional hooks to the build process like:
before_run and after_run.
Fixes #541

Do not run build preparations in OSBS when --dry-run is used

---

cekit/descriptor/image.py
tests/test_integ_builder_osbs.py

We shuld initialize the 'osbs' section no matter what. This will
make it possible to set parameters for it properly later in the
process.
Fixes #542

Setting default OSBS extra_dir parameter properly

---

docs/handbook/building/builder-engines.rst

Previously showing as 'commit-msg'

Fixes OSBS builder parameter '--commit-message' in docs

---

cekit/builder.py
cekit/builders/osbs.py
cekit/cli.py
docs/handbook/building/parameters.rst
tests/test_builder.py
tests/test_unit_args.py
tests/test_validate.py

This adds a --validate switch to the build command. It interrupts the build process
early in the stage, just after the model is prepared and validated. This
is similar to --dry-run with the difference that --dry-run additionally generates
required files for the selected builder (which --validate does not).
This required redesigning build hooks which are now following:
1. prepare()
2. before_generate()
3. generate()
4. before_build()
5. run()
Fixes #551

Add support for validating image sources

---

cekit/templates/template.jinja
tests/test_validate.py

Per https://github.com/rpm-software-management/microdnf/issues/27 libdnf seems to have an issue on cache data, when doing multiple / subsequent package installs
Therefore clean the microdnf cache after the each install command
to avoid this
Also add a test to check the 'clean all' snippet is present in resulting Dockerfile, when using microdnf as a package manager
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

[KEYCLOAK-10694] Add workaround for microdnf RH BZ#1700341 issue

---

cekit/descriptor/image.py
cekit/descriptor/resource.py
cekit/templates/template.jinja
docs/guidelines/local-development.rst
tests/test_dockerfile.py
tests/test_unit_resource.py
tests/test_validate.py

This chnges the way we generate Dockerfile so that
artifacts and modules are not copied at the beginning of
the Dockerfile. This makes it possible to reuse
Docker (and other builder's) cache for content that
was not changed.
To make use of rapid development with cached you need to
make sure the module you modify is installed later in the process
because this invalidates cache and all modules installed
later will need to be executed again.
If you use Docker builder, use the `--no-squash` option.
Without this, the squash post processing will remove all
intermediate container images created at the original image build time
removing the cache at the same time.
Fixes #544

Copy modules and artifacts when module is processed

---

cekit/tools.py
tests/test_unit_tools.py

This helps to debug issues related to certificate validation
issues where the certifi library overrides what is provided
system-wide.
Fixes #577

When certifi is available, add a warning

---

cekit/descriptor/execute.py
cekit/generator/base.py
cekit/template_helper.py

This shows less warning, especially for modules without version specified. Without this change it would be printed 3 times. Additionally changes logging level to debug for missing name in scripts. We do not want to spam users with it.

Improve logging - show less warnings

---

cekit/builders/osbs.py
cekit/cli.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_dockerfile.py
tests/test_integ_builder_osbs.py
tests/test_unit_args.py

Add a --sync-only parameter to the OSBS builder engine. When specified
the content will be generated, synced with dist git and afterwards
the process will be stopped meaning that the OSBS build will
not be trigerred.
Fixes #587

Add support for syncing with dist-git without running an OSBS build

---

cekit/builders/osbs.py
cekit/cli.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_integ_builder_osbs.py
tests/test_unit_args.py

This makes it possible to run the OSBS build in a non-interactive
mode by answering any questions with 'Yes'.
This is helpful when using CEKit in an automated CI/CD environment
to trigger OSBS builds.
Fixes #589

Add --assume-yes (-y) switch to OSBS builder

---

.circleci/config.yml
cekit/builders/buildah.py
cekit/builders/podman.py
cekit/cli.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_integ_multi_stage.py
tests/test_unit_args.py

This makes use of the squashing feature of the Buildah and
Podman builder. We squash images by default now.
It is possible to disable squashing by using the: `--no-squash`
switch for both: Podman and Buildah builders.
Additionally the `BUILDAH_LAYERS` environment variable documentation
was adeded for above builders.
Fixes #441
Fixes #597
Fixes #598

Add support for squashing for Buildah and Podman

---

cekit/builder.py
cekit/builders/osbs.py
cekit/cli.py
cekit/descriptor/osbs.py
docs/descriptor/includes/image/osbs.rst
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_integ_builder_osbs.py

Makes it possible to define koji target in the image desciptor.
The --koji-target switch from OSBS builder was marked as deprecated.
Fixes #591

Add support for specifying koji target in descriptor

---

.circleci/config.yml
cekit/descriptor/resource.py
docs/_ext/schema.py
docs/conf.py
docs/descriptor/includes/artifacts.rst

This is a PoC where the schema of particular element is shown
in the documentation. This supports only artifacts for now,
but it could be possibly extended for other elements
in the future.
Fixes #607

Show schema for artifacts in documentation

---

cekit/builders/osbs.py
cekit/cli.py
cekit/version.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_dockerfile.py
tests/test_integ_builder_osbs.py
tests/test_unit_args.py

This is a one-off release to backport two features into the 3.2.x codebase:
1. Support for `--assume-yes` OSBS builder switch
1. Support for `--sync-only` OSBS builder switch

Release 3.2.1

---

cekit/builders/osbs.py
cekit/cli.py
cekit/version.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_dockerfile.py
tests/test_integ_builder_osbs.py
tests/test_unit_args.py

This is a one-off release to backport two features into the 3.3.x codebase:
1. Support for `--assume-yes` OSBS builder switch
1. Support for `--sync-only` OSBS builder switch

Release 3.3.2

---

cekit/builder.py
cekit/builders/osbs.py
cekit/cli.py
docs/handbook/building/builder-engines.rst
tests/test_builder.py
tests/test_integ_builder_osbs.py
tests/test_unit_args.py

It was deprecated in 3.5. In this version we remove it.
Fixes #601

Remove --koji-target OSBS builder parameter from CLI

---

cekit/descriptor/resource.py
tests/test_unit_resource.py

Git resource handling uses now deterministic way for generating
target directories where these should be cloned.
If the 'target' key is defined, it will be used as-is. If the
'target' key is missing, the value of the 'name' key is used.
If the 'name' key is not used, then the target diretory is
computed based on the URL of the git repository. This will be the
base name of the URL, without any extensions (like '.git').
There should be no case where we have two module repositories
defined that have the same target directory. In such case this is
a mistake in configuration and proper 'name' or 'target' keys
should be set.
Fixes #621

Deterministic git resource handling

---

.circleci/config.yml
cekit/builders/osbs.py
cekit/generator/osbs.py
tests/test_integ_builder_osbs.py

If all artifacts are handled by lookaside cache
(or there are no artifacts) we want to make sure the
fetch-artifacts-url.yaml does not exists in the dist-git
repository.
Fixes #629

Do not leave fetch-artifacts-url.yaml if not used

---

cekit/descriptor/osbs.py
tests/test_integ_builder_osbs.py

Make sure that the osbs section can be correctly merged with overrides.
In some cases the container.yaml file was not generated to incorrect
handling of merging.
Fixes #631

Fix osbs section merging

---

cekit/descriptor/resource.py
tests/test_unit_resource.py

This makes it possible to use any valid reference as the
'ref' value for a Git resource. This type of resource is used
for example for defining module registries.
This accepts now branch, tag, commit or any other valid ref.
Fixes #618

Allow for anything in module git ref

---

cekit/generator/base.py
tests/test_unit_image.py

When retrieving modules from registry, in case of missing
version, we print  warning only when there are more than one
module in registry with the same name.
Fixes #617

Print missing module version warning only when needed

---

cekit/descriptor/image.py
tests/test_unit_image.py

This rewrites how overrides are handled for content sets.
From now all the work to merge packages is offloaded to the merge
algorithm.
Fixes #628

Fix content sets overrides

---

cekit/generator/base.py
cekit/generator/docker.py
cekit/generator/osbs.py
tests/images/multi-stage/modules/build/build.sh
tests/images/multi-stage/modules/build/module.yaml

This fixes an issue if an artifact was defined in a builder image, CEKit
failed to handle it. Now, CEKit properly obtains the artifacts and it becomes
available for consumption.
Fixes #642

Handle artifacts defined in builder images

---

cekit/templates/template.jinja
tests/images/multi-stage/image.yaml
tests/images/multi-stage/modules/app/module.yaml
tests/images/multi-stage/modules/setuptools/module.yaml
tests/test_integ_podman.py

In case of multi-stage builds using different images with different
operating systems it is required to specify correct package
managers so that provided packages can be installed properly.
This commit fixes a bug where the package manager specification
was ignored in builder images and instead the target package manager
was used. Now, the specified package manager in the image will be used.
Fixes #646

Properly handle package managers in multi-stage builds

---

cekit/templates/template.jinja

Licensing of generated files should not be imposed
by the build tool.
Fixes #405

Remove the ASL 2.0 license from generated Dockerfile

---

cekit/builders/osbs.py
cekit/descriptor/resource.py
cekit/generator/osbs.py
tests/images/multi-stage/image.yaml
tests/test_builder.py
tests/test_integ_builder_osbs.py

Most important change is to take into account artifacts in all images
when preparing the sync with dist-git. Previously only the terget image
was handled which lead to incorrect results.
Other changes:
* Cleaning up dist-git from any untracked files or directories
* More logging
Fixes #649

Improvements in handling multi-stage builds in OSBS

---

.gitignore
tests/test_integ_test_behave.py
tests/test_validate.py
tox.ini

While running the _complete_ suite requires all engines (e.g. docker & podman) to be installed, this change is to transparently disable docker based tests if the executable is not installed.

Transparently disable tests if Docker is not installed

---

.github/workflows/cekit.yml
.travis.yml

@goldmann This removes the use of Travis and uses GH Actions for Python 2.7/3.8 under MacOS and Ubuntu.

Add OSX and Python matrix testing. Handle 2.7 testing issues.

---

cekit/__init__.py
cekit/cache/__init__.py
cekit/cache/cli.py
cekit/cli.py
cekit/generator/base.py
cekit/version.py
docs/conf.py
setup.py
tests/test_dockerfile.py

The current indirection doesn't work with https://zestreleaser.readthedocs.io/en/latest/versions.html so have tried using one of the methods in https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-version

Change version handling to be zest compatible

---

cekit/descriptor/packages.py
cekit/template_helper.py
docs/descriptor/includes/packages.rst
tests/test_dockerfile.py
tests/test_validate.py

This pull request provides changes to (the development branch of) CEKit to allow the use of ``apt-get`` as a package manager.
These changes are based upon the corresponding pull request for the Alpine ``apk`` package manager #612 corresponding to the enhancement issue #609 
Following the example of the PR #612 we have added:
1. changes to the templating system (via template_helper.py),
2. updated the documentation,
3. added (minimal?) tests corresponding to the use of debian-slim and ``apt-get`` as the distribution and its package manager.
**NOTE:** The Debian ``apt-get`` package manager seems to *require* an "update" step *before* its "install" step. To be completely "correct" we *should* refactor the ``repo_install`` and ``pkg_install`` macros in the ``cekit/templates/template.jinja`` …

added the ability to use Debian based distributions by adding the apt-get package manager

---

.circleci/config.yml
Pipfile
docs/handbook/installation/instructions.rst
requirements.txt

As mentioned in my reply to #696 odcs is really a *runtime* requirement of cekit.
At the moment it is listed as a development time requirement (in Pipfile).
This pull request fixes both the ``requirement.txt`` and ``Pipfile`` requirements files.
This pull request *also* updates the ``docs/handbook/installation/instructions.rst`` file to add a note to users of Debian based distros, that they may need to pre-install the ``libkrb5-dev`` apt package *before* installing using pip.
This pull request has been tested in a clean Ubuntu focal VM using both pip (directly) and virtualenv. (The pre-installation of ``libkrb5-dev`` is *required* to successfully installing cekit with the new odcs requirement).
Fixes #698 (using a much simpler change).

Make odcs a runtime requirement

---

docs/getting-started/modules.rst

1. change from yml to yaml to keep consistency.
2. I got "CekitError: There are no modules with 'tomcat' name available" when it was yml

update tomcat module file extention to yaml

---

docs/descriptor/includes/image/osbs.rst

Include an example of every (sub) key for OSBS configuration in
the example YAML at the top of the page.
It was not clear enough to me where in the osbs heirarchy the
`koji_target` key belonged from the documentation alone, and I
had to double check by reading the source code.
I've ordered the keys to match the order of descriptions below.

Docs: Include all keys in top-most OSBS example

---

cekit/test/behave_runner.py
tests/test_integ_test_behave.py

The docker image name (including tag) is passed directly to behave as the name of a test tag if the docker image name does not include a slash. Behave won't accept test tags that have a non-integer value after the colon. Given CEKit design, this means it is not possible to test an image that has a docker tag other than "latest" or something that can be coerced to an integer using python's `int` function. This changes that behaviour to never pass the docker tag on to behave (i.e anything after a colon).
This is intended to fix #779.
However, looking carefully at this bit of code, I can see no way to fix #779 without also changing existing behaviour of CEKit here, which feels to me somewhat convoluted. Therefore, this PR may not be the best way to resolve the problem.

Issue 779: Change how docker tags are passed to behave tags

---

cekit/descriptor/image.py
cekit/templates/template.jinja
docs/descriptor/includes/packages/manager.rst
docs/handbook/modules/image_order.rst
docs/handbook/modules/index.rst
docs/handbook/modules/merging.rst
setup.cfg
tests/test_integ_builder_osbs.py
tests/test_integ_install_ordering.py

Fix handling of package managers in included repositories. Improve documentation.
Revert "Install modules (including executions) *after* packages are installed, not before."
This reverts commit e9410afcadd13a13a7d8a57e23ce6666ec038ecc.
Fixes #805

Revert changes for module processing order.

---

cekit/templates/template.jinja
tests/test_dockerfile.py

Fixes #813
If the installable package contains the version, then the package listing command (`dpkg-query --list`) throws an error because it appends the version with the package name in the search query.
The error looks like this,
`dpkg-query --list xyz=1.x.y' returned a non-zero code: 1`
This PR fixes that issue simply by stripping the version part and using only the package name as the input for `dpkg-query --list` command.

Issue-813: Stripping package version in package listing command

---

.circleci/config.yml
.github/workflows/cekit.yml
requirements.txt

Fix https://github.com/cekit/cekit/issues/830
Running CEKit with `22.x` packaging version will throw the following error:
```
from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/alampare/miniconda3/envs/cekit-4.4/lib/python3.10/site-packages/packaging/version.py)
```
This was introduced since `packaging=22.0` [1]:
```
Remove LegacySpecifier and LegacyVersion (issue:`407`)
```
The fastest solution would be to restrict the `packaging` version to `<22.0` in the `requirements.txt`
[1] https://github.com/pypa/packaging/blob/main/CHANGELOG.rst#220---2022-12-07

[ISSUE-830] restrict packaging version to <22.0

---

docs/handbook/testing/behave.rst

Edited via the GitHub web UI, ap[ologies for the branch in main repo than the fork (it didn't give me the option to do that). Branch can safely be deleted if/when merged.
Fixes #872

fix broken links to behave tutorial in behave.rst

---

.github/workflows/cekit.yml
Makefile
tox.ini

Python 3.12 release schedule: https://peps.python.org/pep-0693/

Add Python 3.12 to CI tests

---

Pipfile
requirements.txt

CEKit requires pykwalify which implicitly brings in ruamel. In ruamel 0.18.4 ( https://sourceforge.net/p/ruamel-yaml/code/ci/08d87cada1f6e5fedde079b55536061e4fe246a0/#diff-7 ) has `from __future__ import annotations` which is only supported in Python 3.7 so this, for Python 3.6, uses an earlier version of ruamel.

Fixes for Python 3.6

---

cekit/cli.py
cekit/test/behave_tester.py
cekit/test/collector.py
docs/handbook/testing/behave.rst
tests/test_unit_args.py

Prior to this commit, when cloning the behave-test-steps URI, CEKIt looked up the schema_version set in the descriptor in use, defaulting to cekit.version.schema_version (which was usually 1); prefixed a 'v' to get 'v1' and always switched to that ref ('v1').
Instead, Add a click.option such that we have self.params.steps_ref used as the reference to check out, defaulting to 'v' + cekit.version.schema_version.
Fixes #876.

test: behave: add --steps-ref command

---

cekit/templates/template.jinja
tests/test_dockerfile.py
tests/test_integ_builder_osbs.py
tests/test_validate.py

template.jinja: also clean up /var/lib/{rpm,dnf} for reproducibility

---

cekit/builders/docker_builder.py
tests/test_builder.py
tests/test_unit_builder_docker.py

The old library dates from the days it was called "docker-py", the last release (1.10.6) for which was November 2016 (See https://docker-py.readthedocs.io/en/stable/change-log.html#id156 ) 
Originally I considered locking the version to the _current_ version of docker python library (`constants.DEFAULT_DOCKER_API_VERSION`) but it may move too quick and therefore we switched to using our own constant that the behave suite can also reuse.

Remove support for older docker library. 

---

.github/workflows/cekit.yml

Github action default for MacOS version has changed and also podman 5 requires >=13.

Change MacOS version

---

cekit/builders/docker_builder.py
cekit/generator/base.py
cekit/test/behave_runner.py

Fixes #904 
This still allows missing modules to be masked to be handled later by the dependency_handler but serious import issues are now revealed. Tested on https://hub.docker.com/layers/library/amazonlinux/2/images/sha256-648d4061d73ffae7b0270bf7ed6130154bb5fd340ea02ab690eab84a182f9840 : 
```
(cekit) bash-4.2# cekit -v build docker 
Traceback (most recent call last):
File "/root/cekit/bin/cekit", line 33, in <module>
sys.exit(load_entry_point('cekit', 'console_scripts', 'cekit')())
File "/root/cekit/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/root/cekit/lib/python3.7/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/root/cekit/lib/python3.7/site-packages/click/core.py", line 1688, in invoke …
```

Only mask ModuleNotFound not ImportError

---

cekit/templates/template.jinja
tests/test_dockerfile.py

The post-install clean-up is too zealous, and breaks the use of rpm in the resulting images.
Fixes: #905.

Don't remove /var/lib/rpm (#905)

---

cekit/builder.py
cekit/builders/oci_builder.py
cekit/generator/base.py
cekit/generator/behave.py
cekit/generator/docker.py
cekit/generator/osbs.py
cekit/template_helper.py
cekit/templates/template.jinja
cekit/test/behave_tester.py
cekit/tools.py
tests/test_builder.py
tests/test_dockerfile.py
tests/test_integ_podman.py
tests/test_unit_generator_docker.py
tests/test_unit_tools.py
tests/test_validate.py

Essentially if CEKit squashing is disabled this then moves the packagement management clean next to the package install/remove/etc commands - this reduces the layers and ensures caches are not left lying around.
Fixes #849
This will also reduce the number of layers as mentioned in #593

Clean package management cache when not using squash
